stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest
  

maven-build:
  stage: mavenbuild
  tags:
    - springboot_tag
  script:
    - cd Backend/Splask 
    - mvn package
maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script: 
    - cd Backend/Splask
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

autoDeploy:
  stage: autodeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/Splask
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo
  only: 
    refs: 
      - master
    changes:
      - Backend/**/*

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=`pwd`/Frontend/.gradle
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend && ./gradlew build --stacktrace
  artifacts:
    paths:
      - Frontend/app/build/outputs/

android_test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/Frontend/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - ./gradlew test
